name: CI

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Install Qt
        uses: jurplel/install-qt-action@v2
        with:
          version: 6.11.0
          target: desktop

      - name: Checkout
        uses: actions/checkout@v6

      - name: Configure CMake
        run: cmake -B build -S . -G "Ninja"

      - name: Build
        run: cmake --build build