name: CI

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Install Qt
        uses: jurplel/install-qt-action@v4
        with:
          version: 6.8.3
          target: desktop

      - name: Load MSVC
        uses: ilammy/msvc-dev-cmd@v1

      - name: Copy Deploy
        run: windeployqt rl_tester_snake.exe

      - name: Checkout
        uses: actions/checkout@v6

      - name: Configure CMake
        run: cmake -B build -S . -G "Ninja"

      - name: Build
        run: cmake --build build